/* eslint-disable jsx-a11y/alt-text */
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Modal, Image, Spacer,} from "@nextui-org/react";
import React from "react";
import { Text, Button, Link } from "@nextui-org/react";



const Home: NextPage = () => {
  const [visible, setVisible] = React.useState(false);

  const handler = () => setVisible(true);
  const closeHandler = () => {
    setVisible(false);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>PrepMe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      
  
      <Text
        size={120}
        css={{
          textGradient: "45deg, $blue600 -20%, $pink600 50%",
        }}
        weight="bold"
      >
          PrepMe
      </Text>
      <Text
        h1
        size={28}
        css={{
          textGradient: "45deg, $purple600 -20%, $pink600 100%",
        }}
        weight="bold"
        className="shaked"
      >
        ברוכים הבאים לממלכת חדי הקרן
      </Text>
      <Spacer></Spacer><Spacer></Spacer>
      <Link href="segel">
        <Button size="xl" shadow color="gradient" rounded>
           בואו נתחיל 
        </Button>
        </Link>
      </main>

      <footer className={styles.footer}>
        <div>
          <a onClick={handler}>Roni and Shaked</a>
          <Modal noPadding open={visible} onClose={closeHandler}>
            <Modal.Header
              css={{ position: "absolute", zIndex: "$1", top: 5, right: 8 }}
            ></Modal.Header>
            <Modal.Body>
              <Image
                showSkeleton
                src="/RokedShani.png"
                width={1000}
                height={500}
              />
            </Modal.Body>
          </Modal>
        </div>
      </footer>
    </div>
  );
};

export default Home;
